\section{Abbildungen simulierte Wissensstruktur}
Nachfolgend sind für die simulierte Wissensstruktur $\mathcal{K}_s$ die Parameterschätzungen in Abhängigkeit der wahren Parameterwerte abgebildet. Dies geschieht für jedes Modell und jeden Dezimierungsmechanismus. Bei keiner Verzerrung sollten die Schätzungen auf der 1. Winkelhalbierenden liegen.


\begin{figure}[hbtp]
\begin{center}
<<echo=FALSE, results=hide>>=
ag_plot <- aggregate(estim_value ~ cond + model + para_q + para, data_t1, mean)
ag_plot$true_value <- aggregate(true_value ~ cond + model + para_q + para, data_t1, max)[, 5]
l.mat <- matrix(c(rep(c(1, 2, 3, 4, 5, 6, 7, 8), each = 5), rep(c(9, 10, 11, 12, 13), each = 4)), 3, 20, byrow = TRUE)

# BLIM_COMP
pdf("plots/blim_comp_bias.pdf", width = 5.5, height = 5.5, pointsize = 12, family = "CM Roman")
par(mgp = c(1.3, .7, 0), mar = c(3.2, 2.5, .5, 0), oma = c(.5, 1, 1, 0.4))
layout(l.mat[c(rep(1:2, each = 5), rep(3, 4)) , ])

model <- "BLIM_COMP"
cond <- c("mc_10", "mc_20", "ks_10", "ks_20", 
          "mc_30", "mc_40", "ks_30", "ks_40", 
          "iks_C1", "iks_C2", "iks_C3", "iks_C4", "iks_C5")
mu_q <-  c(.1, .2,  0,  0, 
           .3, .4,  0,  0, 
           .45, .35, .25, .15, .05)
mu_q_ <- c(.1, .2, .2, .4, 
           .3, .4, .6, .8, 
           .05, .15, .25, .35, .45) 
labels <- c(expression("mc"[10]), expression("mc"[20]), expression("ks"[10]), expression("ks"[20]),
            expression("mc"[30]), expression("mc"[40]), expression("ks"[30]), expression("ks"[40]),
            expression("iks"[C1]), expression("iks"[C2]), expression("iks"[C3]), expression("iks"[C4]), expression("iks"[C5]))
for(i in 1:13){
plot(estim_value ~ true_value, 
     ag_plot[ag_plot$cond  == cond[i] & 
             ag_plot$model == model &
             ag_plot$para  == "beta", ],
     pch = 19, xlab = "", cex = .6,
     ylab = "", ylim = c(0, .6), xlim = c(0, .1))
points(estim_value ~ true_value, 
       ag_plot[ag_plot$cond  == cond[i] & 
             ag_plot$model == model &
             ag_plot$para  == "eta", ], cex = .6, pch = 19, col = "blue")

abline(a = 0, b = 1, lw = 1.2)

mtext(labels[i], 3, cex = .75, padj = -.2)
}

par(xpd = NA)
segments(-.65, 0.73, x1 = 0.11, y1 = 0.73, lty = 2)
segments(-.278, 0.73, x1 = -.278, y1 = 5, lty = 2)
legend(x = .01, y = 2.9, legend = c("beta", "eta"), pch = c(19, 19), col = c("black", "blue"))
par(xpd = FALSE)

mtext("Wahrer Parameterwert", 1, outer = T, padj = -0.9)
mtext("Parameterschätzung", 2, outer = T, padj = 0.7)

dev.off()
@
\includegraphics[width=.99\textwidth]{plots/blim_comp_bias}
\end{center}
\caption[Parameterschätzung des BLIM\textsubscript{COMP} für $\mathcal{K}_s$]{Parameterschätzung mit dem BLIM\textsubscript{COMP} in Abhängigkeit des wahren Parameterwertes. Die durchgehende Linie zeigt die 1. Winkelhalbierende.}
\end{figure}

\begin{figure}[hbtp]
\begin{center}
<<echo=FALSE, results=hide>>=

# BLIM_MAW
pdf("plots/blim_maw_bias.pdf", width = 5.5, height = 6, pointsize = 12, family = "CM Roman")
par(mgp = c(1.3, .7, 0), mar = c(3.2, 2.5, .5, 0), oma = c(.5, 1, 1, 0.4))
layout(l.mat[c(rep(1:2, each = 5), rep(3, 4)) , ])

model <- "BLIM_MAW"
cond <- c("mc_10", "mc_20", "ks_10", "ks_20", 
          "mc_30", "mc_40", "ks_30", "ks_40", 
          "iks_C1", "iks_C2", "iks_C3", "iks_C4", "iks_C5")
mu_q <-  c(.1, .2,  0,  0, 
           .3, .4,  0,  0, 
           .45, .35, .25, .15, .05)
mu_q_ <- c(.1, .2, .2, .4, 
           .3, .4, .6, .8, 
           .05, .15, .25, .35, .45) 
labels <- c(expression("mc"[10]), expression("mc"[20]), expression("ks"[10]), expression("ks"[20]),
            expression("mc"[30]), expression("mc"[40]), expression("ks"[30]), expression("ks"[40]),
            expression("iks"[C1]), expression("iks"[C2]), expression("iks"[C3]), expression("iks"[C4]), expression("iks"[C5]))
for(i in 1:13){
plot(estim_value ~ true_value, 
     ag_plot[ag_plot$cond  == cond[i] & 
             ag_plot$model == model &
             ag_plot$para  == "beta", ],
     pch = 19, xlab = "", cex = .6,
     ylab = "", ylim = c(0, .5), xlim = c(0, .1))
points(estim_value ~ true_value, 
       ag_plot[ag_plot$cond  == cond[i] & 
             ag_plot$model == model &
             ag_plot$para  == "eta", ], cex = .6, pch = 19, col = "blue")

abline(a = mu_q[i], b = (1 - mu_q[i]), lty = 2)
abline(a = 0, b = (1 - mu_q_[i]), lty = 2)
abline(a = 0, b = 1, lw = 1.2)

mtext(labels[i], 3, cex = .75, padj = -.2)
}

par(xpd = NA)
segments(-.65, 0.62, x1 = 0.11, y1 = 0.62, lty = 2)
segments(-.278, 0.62, x1 = -.278, y1 = 5, lty = 2)
legend(x = .01, y = 2.35, legend = c("beta", "eta"), pch = c(19, 19), col = c("black", "blue"))
par(xpd = FALSE)

mtext("Wahrer Parameterwert", 1, outer = T, padj = -0.9)
mtext("Parameterschätzung", 2, outer = T, padj = 0.7)

dev.off()
@
\includegraphics[width=.99\textwidth]{plots/blim_maw_bias}
\end{center}
\caption[Parameterschätzung des BLIM\textsubscript{MAW} für $\mathcal{K}_s$]{Parameterschätzung mit dem BLIM\textsubscript{MAW} in Abhängigkeit des wahren Parameterwertes. Die gestrichelte Linie zeigt die theoretisch zu erwartende Verzerrung, die durchgehende Linie die 1. Winkelhalbierende.}
\end{figure}

\begin{figure}[hbtp]
\begin{center}
<<echo=FALSE, results=hide>>=


# IMBLIM
pdf("plots/imblim_bias.pdf", width = 5.5, height = 6, pointsize = 12, family = "CM Roman")
par(mgp = c(1.3, .7, 0), mar = c(3.2, 2.5, .5, 0), oma = c(.5, 1, 1, 0.4))
layout(l.mat[c(rep(1:2, each = 5), rep(3, 4)) , ])

model <- "IMBLIM"
cond <- c("mc_10", "mc_20", "ks_10", "ks_20", 
          "mc_30", "mc_40", "ks_30", "ks_40", 
          "iks_C1", "iks_C2", "iks_C3", "iks_C4", "iks_C5")
mu_q <-  c(.1, .2,  0,  0, 
           .3, .4,  0,  0, 
           .45, .35, .25, .15, .05)
mu_q_ <- c(.1, .2, .2, .4, 
           .3, .4, .6, .8, 
           .05, .15, .25, .35, .45) 
labels <- c(expression("mc"[10]), expression("mc"[20]), expression("ks"[10]), expression("ks"[20]),
            expression("mc"[30]), expression("mc"[40]), expression("ks"[30]), expression("ks"[40]),
            expression("iks"[C1]), expression("iks"[C2]), expression("iks"[C3]), expression("iks"[C4]), expression("iks"[C5]))
for(i in 1:13){
plot(estim_value ~ true_value, 
     ag_plot[ag_plot$cond  == cond[i] & 
             ag_plot$model == model &
             ag_plot$para  == "beta", ],
     pch = 19, xlab = "", cex = .6,
     ylab = "", ylim = c(0, .55), xlim = c(0, .1))
points(estim_value ~ true_value, 
       ag_plot[ag_plot$cond  == cond[i] & 
             ag_plot$model == model &
             ag_plot$para  == "eta", ], cex = .6, pch = 19, col = "blue")

abline(a = 0, b = 1, lw = 1.2)

mtext(labels[i], 3, cex = .75, padj = -.2)
}

par(xpd = NA)
segments(-.65, 0.68, x1 = 0.11, y1 = 0.68, lty = 2)
segments(-.278, 0.68, x1 = -.278, y1 = 5, lty = 2)
legend(x = .01, y = 2.55, legend = c("beta", "eta"), pch = c(19, 19), col = c("black", "blue"))
par(xpd = FALSE)

mtext("Wahrer Parameterwert", 1, outer = T, padj = -0.9)
mtext("Parameterschätzung", 2, outer = T, padj = 0.7)

dev.off()
@
\includegraphics[width=.99\textwidth]{plots/imblim_bias}
\end{center}
\caption[Parameterschätzung des IMBLIM für $\mathcal{K}_s$]{Parameterschätzung mit dem IMBLIM in Abhängigkeit des wahren Parameterwertes. Die durchgehende Linie zeigt die 1. Winkelhalbierende.}
\end{figure}


\begin{figure}[hbtp]
\begin{center}
<<echo=FALSE, results=hide>>=

# MissBLIM
pdf("plots/missblim_bias.pdf", width = 5.5, height = 6, pointsize = 12, family = "CM Roman")
par(mgp = c(1.3, .7, 0), mar = c(3.2, 2.5, .5, 0), oma = c(.5, 1, 1, 0.4))
layout(l.mat[c(rep(1:2, each = 5), rep(3, 4)) , ])

model <- "MissBLIM"
cond <- c("mc_10", "mc_20", "ks_10", "ks_20", 
          "mc_30", "mc_40", "ks_30", "ks_40", 
          "iks_C1", "iks_C2", "iks_C3", "iks_C4", "iks_C5")
mu_q <-  c(.1, .2,  0,  0, 
           .3, .4,  0,  0, 
           .45, .35, .25, .15, .05)
mu_q_ <- c(.1, .2, .2, .4, 
           .3, .4, .6, .8, 
           .05, .15, .25, .35, .45) 
labels <- c(expression("mc"[10]), expression("mc"[20]), expression("ks"[10]), expression("ks"[20]),
            expression("mc"[30]), expression("mc"[40]), expression("ks"[30]), expression("ks"[40]),
            expression("iks"[C1]), expression("iks"[C2]), expression("iks"[C3]), expression("iks"[C4]), expression("iks"[C5]))
for(i in 1:13){
plot(estim_value ~ true_value, 
     ag_plot[ag_plot$cond  == cond[i] & 
             ag_plot$model == model &
             ag_plot$para  == "beta", ],
     pch = 19, xlab = "", cex = .6,
     ylab = "", ylim = c(0, .15), xlim = c(0, .1))
points(estim_value ~ true_value, 
       ag_plot[ag_plot$cond  == cond[i] & 
             ag_plot$model == model &
             ag_plot$para  == "eta", ], cex = .6, pch = 19, col = "blue")

abline(a = 0, b = 1, lw = 1.2)

mtext(labels[i], 3, cex = .75, padj = -.2)
}

par(xpd = NA)
segments(-.65, 0.185, x1 = 0.11, y1 = 0.185, lty = 2)
segments(-.278, 0.185, x1 = -.278, y1 = 5, lty = 2)
legend(x = .01, y = .72, legend = c("beta", "eta"), pch = c(19, 19), col = c("black", "blue"))
par(xpd = FALSE)

mtext("Wahrer Parameterwert", 1, outer = T, padj = -0.9)
mtext("Parameterschätzung", 2, outer = T, padj = 0.7)

dev.off()
@
\includegraphics[width=.99\textwidth]{plots/missblim_bias}
\end{center}
\caption[Parameterschätzung des MissBLIM für $\mathcal{K}_s$]{Parameterschätzung mit dem MissBLIM in Abhängigkeit des wahren Parameterwertes. Die durchgehende Linie zeigt die 1. Winkelhalbierende.}
\end{figure}