\subsection*{$\beta$-Schätzung: $N = 10000$}
Nachfolgend sind für die empirischen Wissensstrukturen $\mathcal{K}_{err}$, $\mathcal{K}_{geh}$ und $\mathcal{K}_{ges}$ die $\beta$-Parameterschätzungen in Abhängigkeit der wahren Parameterwerte für eine simulierte Stichprobengröße von $N = 10000$ abgebildet. Dies geschieht für jedes Modell und jeden Dezimierungsmechanismus. Bei keiner Verzerrung sollten die Schätzungen auf der 1. Winkelhalbierenden liegen.


%Skala Erregbarkeit
<<echo=FALSE, results=hide>>=
#
## load emp WS fitted models
load("data/fitted_models_tKS_fpi_err_10000_200_42.rda")

# remove estimates that did not converge
#data_estim_raw <- data_estim
not_converged_emp_err <- unique(data_estim[(!is.na(data_estim$converged) & data_estim$converged == FALSE), c("cond", "model", "N", "iterations", "set_num")])
data_estim <- data_estim[data_estim$converged, ]

# Table Bias 
data_estim$bias <- data_estim$estim_value - data_estim$true_value
data_estim_err <- data_estim
data_t1_emp <- subset(data_estim, para %in% c("beta", "eta"))

data_t1_emp$model <- factor(data_t1_emp$model)
data_t1_emp$para  <- factor(data_t1_emp$para)
# works also with subset of data!
level_cond <- c(paste0("mc_", c(1, 5, 10, 15)), paste0("ks_", c(1, 5, 10, 15)), paste0("iks_C", 1:4))
data_t1_emp$cond  <- factor(data_t1_emp$cond, levels = level_cond[which(level_cond %in% levels(factor(data_t1_emp$cond)))])

data_t1_emp_err <- data_t1_emp
@
%Skala Gehemmtheit
<<echo=FALSE, results=hide>>=
#
## load emp WS fitted models
load("data/fitted_models_tKS_fpi_geh_10000_200_42.rda")

# remove estimates that did not converge
#data_estim_raw <- data_estim
not_converged_emp_geh <- unique(data_estim[(!is.na(data_estim$converged) & data_estim$converged == FALSE), c("cond", "model", "N", "iterations", "set_num")])
data_estim <- data_estim[data_estim$converged, ]

# Table Bias 
data_estim$bias <- data_estim$estim_value - data_estim$true_value
data_estim_geh <- data_estim
data_t1_emp <- subset(data_estim, para %in% c("beta", "eta"))

data_t1_emp$model <- factor(data_t1_emp$model)
data_t1_emp$para  <- factor(data_t1_emp$para)
# works also with subset of data!
level_cond <- c(paste0("mc_", c(1, 5, 10, 15)), paste0("ks_", c(1, 5, 10, 15)), paste0("iks_C", 1:4))
data_t1_emp$cond  <- factor(data_t1_emp$cond, levels = level_cond[which(level_cond %in% levels(factor(data_t1_emp$cond)))])

data_t1_emp_geh <- data_t1_emp
@
%Skala Gesundheitssorgen
<<echo=FALSE, results=hide>>=
#
## load emp WS fitted models
load("data/fitted_models_tKS_fpi_ges_10000_200_42.rda")

# remove estimates that did not converge
#data_estim_raw <- data_estim
not_converged_emp_err <- unique(data_estim[(!is.na(data_estim$converged) & data_estim$converged == FALSE), c("cond", "model", "N", "iterations", "set_num")])
data_estim <- data_estim[data_estim$converged, ]

# Table Bias 
data_estim$bias <- data_estim$estim_value - data_estim$true_value
data_estim_ges <- data_estim
data_t1_emp <- subset(data_estim, para %in% c("beta", "eta"))

data_t1_emp$model <- factor(data_t1_emp$model)
data_t1_emp$para  <- factor(data_t1_emp$para)
# works also with subset of data!
level_cond <- c(paste0("mc_", c(1, 5, 10, 15)), paste0("ks_", c(1, 5, 10, 15)), paste0("iks_C", 1:4))
data_t1_emp$cond  <- factor(data_t1_emp$cond, levels = level_cond[which(level_cond %in% levels(factor(data_t1_emp$cond)))])

data_t1_emp_ges <- data_t1_emp
@


\begin{figure}[h!]
\begin{center}
<<echo=FALSE, results=hide>>=
ag_plot_err <- aggregate(estim_value ~ cond + model + para_q + para, data_t1_emp_err, mean)
ag_plot_err$SD <- aggregate(estim_value ~ cond + model + para_q + para, data_t1_emp_err, sd)[, 5]
ag_plot_err$true_value <- aggregate(true_value ~ cond + model + para_q + para, data_t1_emp_err, max)[, 5]

ag_plot_geh <- aggregate(estim_value ~ cond + model + para_q + para, data_t1_emp_geh, mean)
ag_plot_geh$SD <- aggregate(estim_value ~ cond + model + para_q + para, data_t1_emp_geh, sd)[, 5]
ag_plot_geh$true_value <- aggregate(true_value ~ cond + model + para_q + para, data_t1_emp_geh, max)[, 5]

ag_plot_ges <- aggregate(estim_value ~ cond + model + para_q + para, data_t1_emp_ges, mean)
ag_plot_ges$SD <- aggregate(estim_value ~ cond + model + para_q + para, data_t1_emp_ges, sd)[, 5]
ag_plot_ges$true_value <- aggregate(true_value ~ cond + model + para_q + para, data_t1_emp_ges, max)[, 5]

l.mat <- matrix(c(rep(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), each = 5)), 3, 20, byrow = TRUE)

# BLIM_COMP
pdf("plots/blim_comp_bias_emp_beta_n10000.pdf", width = 5.5, height = 5.1, pointsize = 12, family = "CM Roman")
par(mgp = c(1.3, .7, 0), mar = c(3.2, 2.5, .5, 0), oma = c(.5, 1, 2, 0.4))
layout(l.mat[c(rep(1:3, each = 5)) , ])

model <- "BLIM_COMP"
cond <- c("mc_1", "mc_5", "ks_1", "ks_5", 
          "mc_10", "mc_15", "ks_10", "ks_15", 
          "iks_C1", "iks_C2", "iks_C3", "iks_C4")
mu_q <-  c(.01,   .05,   0,    0, 
           .10,   .15,   0,    0, 
           .125,  .075, .03,  .005)
mu_q_ <- c(.01,   .05,  .02,  .1, 
           .10,   .15,  .2,   .3, 
           .005,  .03,  .075, .125) 
labels <- c(expression("mc"[1]), expression("mc"[5]), expression("ks"[1]), expression("ks"[5]),
            expression("mc"[10]), expression("mc"[15]), expression("ks"[10]), expression("ks"[15]),
            expression("iks"[c1]), expression("iks"[c2]), expression("iks"[c3]), expression("iks"[c4]))
for(i in 1:12){
plot(estim_value ~ true_value, 
     ag_plot_err[ag_plot_err$cond  == cond[i] & 
             ag_plot_err$model == model &
             ag_plot_err$para  == "beta", ],
     pch = 19, xlab = "", cex = .7,
     ylab = "", ylim = c(0, .5), xlim = c(0, .5), col = "blue")

with(ag_plot_err[ag_plot_err$cond  == cond[i] & 
                 ag_plot_err$model == model &
                 ag_plot_err$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "blue", lw = .6))
  
points(estim_value ~ true_value, 
       ag_plot_geh[ag_plot_geh$cond  == cond[i] & 
             ag_plot_geh$model == model &
             ag_plot_geh$para  == "beta", ], cex = .7, pch = 19, col = "red")

with(ag_plot_geh[ag_plot_geh$cond  == cond[i] & 
                 ag_plot_geh$model == model &
                 ag_plot_geh$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "red", lw = .6))
  
points(estim_value ~ true_value, 
       ag_plot_ges[ag_plot_ges$cond  == cond[i] & 
             ag_plot_ges$model == model &
             ag_plot_ges$para  == "beta", ], cex = .7, pch = 19, col = "green3")

with(ag_plot_ges[ag_plot_ges$cond  == cond[i] & 
                 ag_plot_ges$model == model &
                 ag_plot_ges$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "green3", lw = .6))
  
abline(a = 0, b = 1, lw = 0.5)

mtext(labels[i], 3, cex = .75, padj = -.2)
}

par(xpd = NA)
segments(-2.2, 0.62, x1 = 0.52, y1 = 0.62, lty = 2)
segments(-.87, 0.62, x1 = -.87, y1 = 2.1, lty = 2)
legend(x = -1.7, y = 2.25, legend = c("Erregbarkeit", "Gehemmtheit", "Gesundheitssorgen"), pch = c(19, 19, 19), col = c("blue", "red", "green3"), horiz = T, bty = "n")
par(xpd = FALSE)

mtext("Wahrer Parameterwert", 1, outer = T, padj = -0.9)
mtext("Parameterschätzung", 2, outer = T, padj = 0.7)

dev.off()
@
\includegraphics[width=.99\textwidth]{plots/blim_comp_bias_emp_beta_n10000}
\end{center}
\caption[$\beta$-Parameterschätzung des BLIM\textsubscript{COMP} für die emp. Wissensstrukturen $(N = 10000)$]{Mittlere $\beta$-Parameterschätzung des BLIM\textsubscript{COMP} in Abhängigkeit des wahren Parameterwertes für jedes der 12 Items der drei empirischen Wissensstrukturen $\mathcal{K}_{err}$, $\mathcal{K}_{geh}$ und $\mathcal{K}_{ges}$ für eine Stichprobengröße von $N = 10000$. Die durchgehende Linie zeigt die 1. Winkelhalbierende und die Standardabweichung ist als Fehlerbalken eingezeichnet.}
\end{figure}


\begin{figure}[hbtp]
\begin{center}
<<echo=FALSE, results=hide>>=

# BLIM_MAW
pdf("plots/blim_maw_bias_emp_beta_n10000.pdf", width = 5.5, height = 5.2, pointsize = 12, family = "CM Roman")
par(mgp = c(1.3, .7, 0), mar = c(3.2, 2.5, .5, 0), oma = c(.5, 1, 2, 0.4))
layout(l.mat[c(rep(1:3, each = 5)) , ])

model <- "BLIM_MAW"
cond <- c("mc_1", "mc_5", "ks_1", "ks_5", 
          "mc_10", "mc_15", "ks_10", "ks_15", 
          "iks_C1", "iks_C2", "iks_C3", "iks_C4")
mu_q <-  c(.01,   .05,   0,    0, 
           .10,   .15,   0,    0, 
           .125,  .075, .03,  .005)
mu_q_ <- c(.01,   .05,  .02,  .1, 
           .10,   .15,  .2,   .3, 
           .005,  .03,  .075, .125) 
labels <- c(expression("mc"[1]), expression("mc"[5]), expression("ks"[1]), expression("ks"[5]),
            expression("mc"[10]), expression("mc"[15]), expression("ks"[10]), expression("ks"[15]),
            expression("iks"[c1]), expression("iks"[c2]), expression("iks"[c3]), expression("iks"[c4]))
for(i in 1:12){
plot(estim_value ~ true_value, 
     ag_plot_err[ag_plot_err$cond  == cond[i] & 
             ag_plot_err$model == model &
             ag_plot_err$para  == "beta", ],
     pch = 19, xlab = "", cex = .7,
     ylab = "", ylim = c(0, .6), xlim = c(0, .5), col = "blue")

with(ag_plot_err[ag_plot_err$cond  == cond[i] & 
                 ag_plot_err$model == model &
                 ag_plot_err$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "blue", lw = .6))
  
points(estim_value ~ true_value, 
       ag_plot_geh[ag_plot_geh$cond  == cond[i] & 
             ag_plot_geh$model == model &
             ag_plot_geh$para  == "beta", ], cex = .7, pch = 19, col = "red")

with(ag_plot_geh[ag_plot_geh$cond  == cond[i] & 
                 ag_plot_geh$model == model &
                 ag_plot_geh$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "red", lw = .6))
  
points(estim_value ~ true_value, 
       ag_plot_ges[ag_plot_ges$cond  == cond[i] & 
             ag_plot_ges$model == model &
             ag_plot_ges$para  == "beta", ], cex = .7, pch = 19, col = "green3")

with(ag_plot_ges[ag_plot_ges$cond  == cond[i] & 
                 ag_plot_ges$model == model &
                 ag_plot_ges$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "green3", lw = .6))
  
abline(a = 0, b = 1, lw = 0.5)
abline(a = mu_q[i], b = (1 - mu_q[i]), lty = 2, lw = .5)

mtext(labels[i], 3, cex = .75, padj = -.2)
}

par(xpd = NA)
segments(-2.2, 0.75, x1 = 0.52, y1 = 0.75, lty = 2)
segments(-.87, 0.75, x1 = -.87, y1 = 2.4, lty = 2)
legend(x = -1.7, y = 2.68, legend = c("Erregbarkeit", "Gehemmtheit", "Gesundheitssorgen"), pch = c(19, 19, 19), col = c("blue", "red", "green3"), horiz = T, bty = "n")
par(xpd = FALSE)

mtext("Wahrer Parameterwert", 1, outer = T, padj = -0.9)
mtext("Parameterschätzung", 2, outer = T, padj = 0.7)

dev.off()
@
\includegraphics[width=.99\textwidth]{plots/blim_maw_bias_emp_beta_n10000}
\end{center}
\caption[$\beta$-Parameterschätzung des BLIM\textsubscript{MAW} für die emp. Wissensstrukturen $(N = 10000)$]{Mittlere $\beta$-Parameterschätzung des BLIM\textsubscript{MAW} in Abhängigkeit des wahren Parameterwertes für jedes der 12 Items der drei empirischen Wissensstrukturen $\mathcal{K}_{err}$, $\mathcal{K}_{geh}$ und $\mathcal{K}_{ges}$ für eine Stichprobengröße von $N = 10000$. Die durchgehende Linie zeigt die 1. Winkelhalbierende und die gestrichelte die theoretisch zu erwartende Verzerrung. Die Standardabweichung ist als Fehlerbalken eingezeichnet.}
\end{figure}

\begin{figure}[hbtp]
\begin{center}
<<echo=FALSE, results=hide>>=

# BLIM_IMBLIM
pdf("plots/imblim_bias_emp_beta_n10000.pdf", width = 5.5, height = 5.2, pointsize = 12, family = "CM Roman")
par(mgp = c(1.3, .7, 0), mar = c(3.2, 2.5, .5, 0), oma = c(.5, 1, 2, 0.4))
layout(l.mat[c(rep(1:3, each = 5)) , ])

model <- "IMBLIM"
cond <- c("mc_1", "mc_5", "ks_1", "ks_5", 
          "mc_10", "mc_15", "ks_10", "ks_15", 
          "iks_C1", "iks_C2", "iks_C3", "iks_C4")
mu_q <-  c(.01,   .05,   0,    0, 
           .10,   .15,   0,    0, 
           .125,  .075, .03,  .005)
mu_q_ <- c(.01,   .05,  .02,  .1, 
           .10,   .15,  .2,   .3, 
           .005,  .03,  .075, .125) 
labels <- c(expression("mc"[1]), expression("mc"[5]), expression("ks"[1]), expression("ks"[5]),
            expression("mc"[10]), expression("mc"[15]), expression("ks"[10]), expression("ks"[15]),
            expression("iks"[c1]), expression("iks"[c2]), expression("iks"[c3]), expression("iks"[c4]))
for(i in 1:12){
plot(estim_value ~ true_value, 
     ag_plot_err[ag_plot_err$cond  == cond[i] & 
             ag_plot_err$model == model &
             ag_plot_err$para  == "beta", ],
     pch = 19, xlab = "", cex = .7,
     ylab = "", ylim = c(0, .5), xlim = c(0, .5), col = "blue")

with(ag_plot_err[ag_plot_err$cond  == cond[i] & 
                 ag_plot_err$model == model &
                 ag_plot_err$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "blue", lw = .6))
  
points(estim_value ~ true_value, 
       ag_plot_geh[ag_plot_geh$cond  == cond[i] & 
             ag_plot_geh$model == model &
             ag_plot_geh$para  == "beta", ], cex = .7, pch = 19, col = "red")

with(ag_plot_geh[ag_plot_geh$cond  == cond[i] & 
                 ag_plot_geh$model == model &
                 ag_plot_geh$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "red", lw = .6))
  
points(estim_value ~ true_value, 
       ag_plot_ges[ag_plot_ges$cond  == cond[i] & 
             ag_plot_ges$model == model &
             ag_plot_ges$para  == "beta", ], cex = .7, pch = 19, col = "green3")

with(ag_plot_ges[ag_plot_ges$cond  == cond[i] & 
                 ag_plot_ges$model == model &
                 ag_plot_ges$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "green3", lw = .6))
  
abline(a = 0, b = 1, lw = 0.5)

mtext(labels[i], 3, cex = .75, padj = -.2)
}

par(xpd = NA)
segments(-2.2, 0.62, x1 = 0.52, y1 = 0.62, lty = 2)
segments(-.87, 0.62, x1 = -.87, y1 = 2.1, lty = 2)
legend(x = -1.7, y = 2.23, legend = c("Erregbarkeit", "Gehemmtheit", "Gesundheitssorgen"), pch = c(19, 19, 19), col = c("blue", "red", "green3"), horiz = T, bty = "n")
par(xpd = FALSE)

mtext("Wahrer Parameterwert", 1, outer = T, padj = -0.9)
mtext("Parameterschätzung", 2, outer = T, padj = 0.7)

dev.off()
@
\includegraphics[width=.99\textwidth]{plots/imblim_bias_emp_beta_n10000}
\end{center}
\caption[$\beta$-Parameterschätzung des IMBLIM für die emp. Wissensstrukturen $(N = 10000)$]{Mittlere $\beta$-Parameterschätzung des IMBLIM in Abhängigkeit des wahren Parameterwertes für jedes der 12 Items der drei empirischen Wissensstrukturen $\mathcal{K}_{err}$, $\mathcal{K}_{geh}$ und $\mathcal{K}_{ges}$ für eine Stichprobengröße von $N = 10000$. Die durchgehende Linie zeigt die 1. Winkelhalbierende und die Standardabweichung ist als Fehlerbalken eingezeichnet.}
\end{figure}

\begin{figure}[hbtp]
\begin{center}
<<echo=FALSE, results=hide>>=

# MissBLIM
pdf("plots/missblim_bias_emp_beta_n10000.pdf", width = 5.5, height = 5.2, pointsize = 12, family = "CM Roman")
par(mgp = c(1.3, .7, 0), mar = c(3.2, 2.5, .5, 0), oma = c(.5, 1, 2, 0.4))
layout(l.mat[c(rep(1:3, each = 5)) , ])

model <- "MissBLIM"
cond <- c("mc_1", "mc_5", "ks_1", "ks_5", 
          "mc_10", "mc_15", "ks_10", "ks_15", 
          "iks_C1", "iks_C2", "iks_C3", "iks_C4")
mu_q <-  c(.01,   .05,   0,    0, 
           .10,   .15,   0,    0, 
           .125,  .075, .03,  .005)
mu_q_ <- c(.01,   .05,  .02,  .1, 
           .10,   .15,  .2,   .3, 
           .005,  .03,  .075, .125) 
labels <- c(expression("mc"[1]), expression("mc"[5]), expression("ks"[1]), expression("ks"[5]),
            expression("mc"[10]), expression("mc"[15]), expression("ks"[10]), expression("ks"[15]),
            expression("iks"[c1]), expression("iks"[c2]), expression("iks"[c3]), expression("iks"[c4]))
for(i in 1:12){
plot(estim_value ~ true_value, 
     ag_plot_err[ag_plot_err$cond  == cond[i] & 
             ag_plot_err$model == model &
             ag_plot_err$para  == "beta", ],
     pch = 19, xlab = "", cex = .7,
     ylab = "", ylim = c(0, .5), xlim = c(0, .5), col = "blue")

with(ag_plot_err[ag_plot_err$cond  == cond[i] & 
                 ag_plot_err$model == model &
                 ag_plot_err$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "blue", lw = .6))
  
points(estim_value ~ true_value, 
       ag_plot_geh[ag_plot_geh$cond  == cond[i] & 
             ag_plot_geh$model == model &
             ag_plot_geh$para  == "beta", ], cex = .7, pch = 19, col = "red")

with(ag_plot_geh[ag_plot_geh$cond  == cond[i] & 
                 ag_plot_geh$model == model &
                 ag_plot_geh$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "red", lw = .6))
  
points(estim_value ~ true_value, 
       ag_plot_ges[ag_plot_ges$cond  == cond[i] & 
             ag_plot_ges$model == model &
             ag_plot_ges$para  == "beta", ], cex = .7, pch = 19, col = "green3")

with(ag_plot_ges[ag_plot_ges$cond  == cond[i] & 
                 ag_plot_ges$model == model &
                 ag_plot_ges$para  == "beta", ],
  arrows(true_value, estim_value - SD, true_value, estim_value + SD, 
         angle = 90, length  = .01, code = 3, col = "green3", lw = .6))
  
abline(a = 0, b = 1, lw = 0.5)

mtext(labels[i], 3, cex = .75, padj = -.2)
}

par(xpd = NA)
segments(-2.2, 0.62, x1 = 0.52, y1 = 0.62, lty = 2)
segments(-.87, 0.62, x1 = -.87, y1 = 2.1, lty = 2)
legend(x = -1.7, y = 2.23, legend = c("Erregbarkeit", "Gehemmtheit", "Gesundheitssorgen"), pch = c(19, 19, 19), col = c("blue", "red", "green3"), horiz = T, bty = "n")
par(xpd = FALSE)

mtext("Wahrer Parameterwert", 1, outer = T, padj = -0.9)
mtext("Parameterschätzung", 2, outer = T, padj = 0.7)

dev.off()
@
\includegraphics[width=.99\textwidth]{plots/missblim_bias_emp_beta_n10000}
\end{center}
\caption[$\beta$-Parameterschätzung des MissBLIM für die emp. Wissensstrukturen $(N = 10000)$]{Mittlere $\beta$-Parameterschätzung des MissBLIM in Abhängigkeit des wahren Parameterwertes für jedes der 12 Items der drei empirischen Wissensstrukturen $\mathcal{K}_{err}$, $\mathcal{K}_{geh}$ und $\mathcal{K}_{ges}$ für eine Stichprobengröße von $N = 10000$. Die durchgehende Linie zeigt die 1. Winkelhalbierende und die Standardabweichung ist als Fehlerbalken eingezeichnet.}
\end{figure}